### PR TITLE
Publish 6.4.0

### PR DESCRIPTION
**Pull request by emclaug2**
### Added

-   Added `blui-inline` attribute styles to `mat-button`. ([#31](https://github.com/brightlayer-ui/angular-themes/issues/31))
-   Added new `outline` and `filled` variant for `<mat-toggle-button>`.([#19](https://github.com/brightlayer-ui/angular-themes/issues/19))

### Fixed

-   Fixed non-center aligned chevron in `<mat-expansion-panel-header>`. ([#50](https://github.com/brightlayer-ui/angular-themes/issues/50))
-   Fixed disabled slider color in `<mat-slider>`. ([#27](https://github.com/brightlayer-ui/angular-themes/issues/27))
-   Fixed text color of active option in `<mat-select>` for light and dark mode. ([#18](https://github.com/brightlayer-ui/angular-themes/issues/18))
-   Fixed dark-mode text and icon color in `<mat-toolbar>`. ([#18](https://github.com/brightlayer-ui/angular-themes/issues/59))

### Changed

-   Updated `mat-form-field` styles ([#48](https://github.com/brightlayer-ui/angular-themes/issues/48)).
-   Updated table styles to match design specifications ([#38](https://github.com/brightlayer-ui/angular-themes/issues/38), [#36](https://github.com/brightlayer-ui/angular-themes/issues/36)).
-   Changed default font-size of `.mat-tooltip` text to `12px`.([#10](https://github.com/brightlayer-ui/angular-themes/issues/10))
-   Changed default height of `.mat-row` to `52px`.([#37](https://github.com/brightlayer-ui/angular-themes/issues/37))
-   Changed `mat-table` header styles. ([#36](https://github.com/brightlayer-ui/angular-themes/issues/36))

Last couple of changes are going to be demo'd tomorrow morning.

### CODE REVIEW

**Comment by huayunh** [comment]
Will you mention "blui-condensed" text field variant in the changelog?

**Comment by huayunh** [comment]
I just plugged the new theme into the angular design patterns. Works fine... with a few broken text fields, presumably bc we used a lot of inline styles. Can you make a follow-up story to fix the design patterns?

**Comment by emclaug2** [comment]
> a follow-up story to fix the design patterns?

Turns out the new input styles didn't account for prefix/suffix icons being wrapped inside of a mat-button.  I've opened up a new PR to fix this issue.

**Comment by jeffvg** [comment]
waiting on another PR

**Comment by huayunh** [comment]
Should be all good to go! Remember to change package.json

**Comment by emclaug2** [comment]
Thank you @huayunh  👍 
I plugged the latest beta package `6.4.0-beta.2` into the design-patterns demo and things are looking much better than before.

**Review by huayunh — APPROVED** [review]
👏👏

**Review by jeffvg — APPROVED** [review]
great work

**Pull request merged**
